### ISSUE TITLE
Ask attorney in screen right after MassAccess Project screen if they have already done the LAR training

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-NoticeOfLimitedAppearances#14]
Use this link if they have not
https://www.mass.gov/doc/uniform-limited-assistance-representation-training-protocol/download

**Comment by sineadvaughan** [comment]
Screen id: attorney certification 
This is the relevant code for this issue.

`id: attorney certification
question: |
  Attorney Certification Notice
subquestion: |
I certify that I have completed an approved LAR information session as required, and that I have signed a written agreement with the Client above to provide the limited representation in this matter as described above. 
  
I also certify that I have served this Notice of Limited Appearance on this Client, all counsel and all Parties not represented by counsel.
fields:
  - no label: agrees_to_certify
    datatype: checkboxes
    minlength: 1
    choices:
      - Certify
    validation messages:
      minlength: |
        You cannot continue unless you check this checkbox.`

Basically we want to break up this Certification into two different screens. 

The first screen should appear before the courts question (screen id: court question). This is the text that should be on this first screen that the Attorney must agree to:

"I certify that I have completed an approved LAR information session as required, and that I have signed a written agreement with the Client above to provide the limited representation in this matter as described above."

For this screen we want to include a link to LAR training and an exit screen if they have not completed the LAR training.

The second screen can remain where it is in the interview as of now but only contain the text below, and the Attorney must agree to it:

" I also certify that I have served this Notice of Limited Appearance on this Client, all counsel and all Parties not represented by counsel."

**Comment by miabonardi** [comment]
@CaroRob Should this function as a kick-out screen if the attorney has not completed the LAR training?

**Comment by CaroRob** [comment]
Yes, and in kickout screen link to URL for training above

**Comment by miabonardi** [comment]
Fixed: 

Added `id: attorney certification 1` screen and if the user (attorney) says "no" they will see `id: Kick out screen for not certifying`
