### ISSUE TITLE
Need an explanation at the start of the interview after screen id: basic questions intro screen

### ISSUE THREAD

**Issue by sineadvaughan** [SuffolkLITLab/docassemble-NoticeOfLimitedAppearances#15]
Our form requires two signatures and how this is going to occur in the interview requires an explanation at the beginning of the interview. This is now indicated at the point of the interview where the Attorney signs their name. Currently the Attorney signs on their computer and the Client signs remotely on their phone.

**Comment by miabonardi** [comment]
Fixed:

Added a question at the beginning `id: client availability` asking if the client is ready to sign. If the client is not, the attorney (user) can still proceed. 

SME said since this form is used by an attorney an intro screen is not necessary.
