### ISSUE TITLE
Consolidate three screens into one screen

### ISSUE THREAD

**Issue by fionolahughes** [SuffolkLITLab/docassemble-NoticeOfLimitedAppearances#2]
For a more efficient interview and as an attorney fills out our form, we want to consolidate three separate screens into one. Screen/Question ID's are as follows: " information on events or issues", "events or issues" and "notice to all other parties".

**Comment by sineadvaughan** [comment]
We have managed to consolidate the screens titled "information on events or issues" and "events or issues". We cannot figure out how to consolidate "notice to all other parties".
