### ISSUE TITLE
Should the `form description` page be changed (the intro)?

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-NoticeOfLimitedAppearances#23]
Right now it has the title of the form _and_ the question about the client in it. The question doesn't really seem connected to the title of the page.

Possible solution: There's no real intro text or form description. Now that the form name will appear on the main intro page, does this form not need an intro page or can this page to just ask about the client?

**Comment by miabonardi** [comment]
@plocket I have changed the question id from "form description" to "client availability." I will ask the SME whether the form requires a description.

**Comment by miabonardi** [comment]
SME says that taking the user right to questions after terms of use is fine.

**Comment by miabonardi** [comment]
SME says that taking the user right to questions after terms of use is fine.
